name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Change to the branch you want to use for deployment
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # You can use other OS options if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Check out your repository's code

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4  # Ensure you're using the correct .NET version
        with:
          dotnet-version: 8.0.x  # Set to the version of .NET your web app uses

      - name: Install dependencies
        run: dotnet restore  # Restore .NET dependencies

      - name: Build the project
        run: dotnet build --no-restore  # Build the .NET project

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish the project
        run: dotnet publish -c Release -o ./publish  # Publish the .NET project

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2  # Deploy to Azure Web App
        with:
          app-name: mywebapp1672  # The name of your Azure Web App
          slot-name: 'staging'  # Optional: for App Service deployment slots
          #publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # This secret contains your deployment credentials
          package: ./publish  # The path to the published files

      - name: Logout Azure CLI
        run: az logout

  deploy_prod:
    needs: deploy_staging
    runs-on: ubuntu-latest
  
    environment:
      name: PROD
      url: ${{ steps.slot_swap.outputs.url }}
  
    steps:
    - name: Login via Azure CLI
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Swap staging slot into production
      id: slot_swap
      run: az webapp deployment slot swap --resource-group ResourceGroupAzureTutorial --name mywebapp1672 --slot staging --subscription d0762df1-a02f-4ecd-9fdd-ddc33fd595e7
        url=$(az webapp show -g ${{ env.rg-name }} -n ${{ env.app-name }} --query "defaultHostName" -o tsv)
        echo "::set-output name=url::http://$url"
    - name: az cli logout
      run: az logout